"""ood_methods_extended.py

Extended OOD baselines + proposed head-gradient matrix-aware methods.

This module follows the same high-level pattern used in `ood_methods.py`:
    - A base `OODMethod` with `compute_ood_scores(loader)`
    - Some methods also implement `fit(id_loader)`

Supported (implemented) methods:
    - MSP, EnergyBased, Odin (as in the original file)
    - FeatureKNN (kNN distance in penultimate features)
    - FeatureMahalanobis (class-conditional Mahalanobis in penultimate features)
    - GradNorm (gradient-norm OOD score on head weights)
    - GradOrth (feature-subspace orthogonality score; simplified faithful variant)
    - LowDimGradResidual (PCA residual on vec(head-gradient))
    - GradVecMahalanobis (gradient embedding + class-conditional Mahalanobis; refactor of original)
    - TwoSidedHeadGradResidual (PROPOSED: two-sided projection residual on head-gradient)
    - TwoSidedHeadGradCodeMahalanobis (PROPOSED: code embedding + Mahalanobis)

Notes:
    - All gradient-based methods here operate on the *head* (final Linear layer).
    - Loaders are assumed to yield (inputs, labels) tuples; labels are optional for scoring.
    - For robustness and comparability, most gradient-based methods expose a `loss_type`.

Author: generated by ChatGPT.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn.functional as F

from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.neighbors import NearestNeighbors
from sklearn.mixture import GaussianMixture


Batch = Union[Tuple[torch.Tensor, torch.Tensor], torch.Tensor]


def _to_device(x: torch.Tensor, device: torch.device) -> torch.Tensor:
    return x.to(device, non_blocking=True) if torch.is_tensor(x) else x


def _iter_inputs(loader: Iterable[Batch]):
    """Yield (inputs, labels_or_None) from a dataloader that may yield inputs only."""
    for batch in loader:
        if isinstance(batch, (list, tuple)) and len(batch) == 2:
            yield batch[0], batch[1]
        else:
            yield batch, None


def _find_last_linear(model: torch.nn.Module) -> Tuple[str, torch.nn.Linear]:
    """Find the last torch.nn.Linear module in the model."""
    last_name, last_mod = None, None
    for name, m in model.named_modules():
        if isinstance(m, torch.nn.Linear):
            last_name, last_mod = name, m
    if last_mod is None:
        raise RuntimeError("Could not find a torch.nn.Linear head in the model.")
    return last_name, last_mod


@dataclass
class HeadIO:
    h: torch.Tensor  # penultimate features input to head: (B, d)
    logits: torch.Tensor  # head output logits: (B, K)


class HeadExtractor:
    """Utility to capture penultimate features (input to last Linear) and logits."""

    def __init__(self, model: torch.nn.Module):
        self.model = model
        self.head_name, self.head = _find_last_linear(model)

    def forward(self, x: torch.Tensor) -> HeadIO:
        device = next(self.model.parameters()).device
        x = _to_device(x, device)

        captured: Dict[str, torch.Tensor] = {}

        def pre_hook(_module, inputs):
            # inputs is a tuple; for Linear it's (h,)
            captured["h"] = inputs[0]

        handle = self.head.register_forward_pre_hook(pre_hook)
        try:
            logits = self.model(x)
        finally:
            handle.remove()

        if "h" not in captured:
            raise RuntimeError("Failed to capture penultimate features (head input).")
        h = captured["h"]
        # Ensure 2D (B,d)
        if h.dim() > 2:
            h = h.view(h.size(0), -1)
        return HeadIO(h=h, logits=logits)


def _loss_from_logits(
    logits: torch.Tensor,
    loss_type: str = "uniform_kl",
    temperature: float = 1.0,
) -> torch.Tensor:
    """Return per-sample loss L(x) given logits.

    Supported loss_type:
        - 'uniform_kl': KL(p || U) (proxy via cross-entropy to uniform)
        - 'entropy': negative entropy (encourage high entropy)
        - 'anti_top1': penalize the predicted top-1 probability
        - 'margin': softplus(z2 - z1) using top-1/top-2 logits
        - 'ce_pred': cross-entropy with predicted class (self-target)
    """
    if temperature <= 0:
        raise ValueError("temperature must be > 0")
    z = logits / temperature
    p = torch.softmax(z, dim=1)
    K = p.size(1)

    if loss_type == "uniform_kl":
        # KL(p || U) = sum p log p - sum p log(1/K) = sum p log p + log K
        # up to constant, minimize negative entropy; for gradient signal, use KL explicitly:
        # KL(p||U) = sum p * (log p - log(1/K))
        # We'll compute directly (stable):
        logp = torch.log(p.clamp_min(1e-12))
        loss = (p * (logp + np.log(K))).sum(dim=1)
        return loss

    if loss_type == "entropy":
        # Negative entropy (lower entropy => larger loss)
        logp = torch.log(p.clamp_min(1e-12))
        ent = -(p * logp).sum(dim=1)
        return -ent

    if loss_type == "anti_top1":
        top1 = p.max(dim=1).values
        # -log(1 - top1) (clamped)
        return -torch.log((1.0 - top1).clamp(1e-6, 1.0))

    if loss_type == "margin":
        top2 = torch.topk(z, k=2, dim=1).values
        z1 = top2[:, 0]
        z2 = top2[:, 1]
        return F.softplus(z2 - z1)

    if loss_type == "ce_pred":
        yhat = torch.argmax(z, dim=1)
        return F.cross_entropy(z, yhat, reduction="none")

    raise ValueError(f"Unknown loss_type: {loss_type}")


def _compute_delta(
    logits: torch.Tensor,
    loss_type: str = "uniform_kl",
    temperature: float = 1.0,
) -> torch.Tensor:
    z = logits / temperature
    p = torch.softmax(z, dim=1)
    if loss_type == "uniform_kl":
        logp = torch.log(p.clamp_min(1e-12))
        ent = (p * logp).sum(dim=1, keepdim=True)
        delta = p * (logp - ent) / temperature
    elif loss_type == "entropy":
        logp = torch.log(p.clamp_min(1e-12))
        ent = (p * logp).sum(dim=1, keepdim=True)
        delta = - (p * (logp - ent)) / temperature
    elif loss_type == "ce_pred":
        yhat = torch.argmax(z, dim=1)
        one_hot = torch.zeros_like(p)
        one_hot.scatter_(1, yhat.unsqueeze(1), 1.0)
        delta = (p - one_hot) / temperature
    else:
        logits_req = logits.detach().requires_grad_(True)
        loss = _loss_from_logits(logits_req, loss_type=loss_type, temperature=temperature)
        delta = torch.autograd.grad(loss.sum(), logits_req, retain_graph=False, create_graph=False)[0]
    return delta


class OODMethod:
    def __init__(self, model: torch.nn.Module):
        self.model = model
        self.model.eval()
        self.extractor = HeadExtractor(model)

    def fit(self, loader: Iterable[Batch]):
        return

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        raise NotImplementedError

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        pass

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError


# ----------------------------
# Simple logit-based baselines
# ----------------------------

class MSP(OODMethod):
    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        p = torch.softmax(logits, dim=1)
        return 1.0 - p.max(dim=1).values.cpu()


class EnergyBased(OODMethod):
    def __init__(self, model: torch.nn.Module, temperature: float = 1.0):
        super().__init__(model)
        self.temperature = temperature

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        energy = -torch.logsumexp(logits / self.temperature, dim=1)
        return energy.cpu()


class Odin(OODMethod):
    def __init__(self, model: torch.nn.Module, epsilon: float = 0.001, temperature: float = 1.0):
        super().__init__(model)
        self.epsilon = epsilon
        self.temperature = temperature

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            x = x.detach().requires_grad_(True)
            logits = self.model(x) / self.temperature
            # maximize max logit -> minimize negative
            loss = -logits.max(dim=1).values.mean()
            self.model.zero_grad(set_to_none=True)
            if x.grad is not None:
                x.grad.zero_()
            loss.backward()
            x_pert = (x + self.epsilon * x.grad.sign()).detach()
            with torch.no_grad():
                logits_p = self.model(x_pert) / self.temperature
                p = torch.softmax(logits_p, dim=1)
                scores.append((1.0 - p.max(dim=1).values).cpu())
        return torch.cat(scores, dim=0)


# ----------------------------
# Feature-based baselines
# ----------------------------

class FeatureKNN(OODMethod):
    def __init__(self, model: torch.nn.Module, k: int = 10, metric: str = "euclidean"):
        super().__init__(model)
        self.k = k
        self.metric = metric
        self.H_train: Optional[torch.Tensor] = None

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        self.H_train = h.cpu()

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.H_train is None:
            raise RuntimeError("FeatureKNN.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        H_test = h.to(device)
        H_train = self.H_train.to(device)
        scores = []
        batch_size = 512
        for i in range(0, H_test.size(0), batch_size):
            h_b = H_test[i:i+batch_size]
            dists = torch.cdist(h_b, H_train, p=2)
            k_dists, _ = torch.topk(dists, self.k, dim=1, largest=False)
            scores.append(k_dists.mean(dim=1).cpu())
        return torch.cat(scores, dim=0)


class FeatureMahalanobis(OODMethod):
    def __init__(self, model: torch.nn.Module, shrinkage: float = 1e-6):
        super().__init__(model)
        self.shrinkage = shrinkage
        self.class_stats: Dict[int, Tuple[torch.Tensor, torch.Tensor]] = {}

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        if y is None:
            raise RuntimeError("FeatureMahalanobis.fit requires labels.")
        device = next(self.model.parameters()).device
        X = h.to(device)
        y = y.reshape(-1).to(device)
        self.class_stats = {}
        class_means = {}
        X_centered = torch.zeros_like(X)
        classes = torch.unique(y)
        for c in classes:
            Xc = X[y == c]
            mu = Xc.mean(dim=0)
            class_means[int(c.item())] = mu
            X_centered[y == c] = Xc - mu
            
        cov = (X_centered.T @ X_centered) / max(1, X.size(0) - 1) + self.shrinkage * torch.eye(X.size(1), device=device)
        inv_cov = torch.linalg.inv(cov)
        
        for c in classes:
            self.class_stats[int(c.item())] = (class_means[int(c.item())].cpu(), inv_cov.cpu())

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if not self.class_stats:
            raise RuntimeError("FeatureMahalanobis.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        X = h.to(device)
        scores = []
        batch_size = 512
        for i in range(0, X.size(0), batch_size):
            x_b = X[i:i+batch_size]
            b_scores = torch.full((x_b.size(0),), float('inf'), device=device)
            for mu, inv_cov in self.class_stats.values():
                mu = mu.to(device)
                inv_cov = inv_cov.to(device)
                d = x_b - mu
                md = torch.sqrt((d @ inv_cov * d).sum(dim=1).clamp_min(0))
                b_scores = torch.min(b_scores, md)
            scores.append(b_scores.cpu())
        return torch.cat(scores, dim=0)


# ----------------------------
# Gradient-based baselines
# ----------------------------

class GradNorm(OODMethod):
    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", p: str = "fro", temperature: float = 1.0):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.p = p

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        h = h.to(next(self.model.parameters()).device)
        logits = logits.to(h.device)
        delta = _compute_delta(logits, loss_type=self.loss_type, temperature=self.temperature)
        if self.p == "fro":
            s = torch.linalg.vector_norm(delta, ord=2, dim=1) * torch.linalg.vector_norm(h, ord=2, dim=1)
        elif self.p == "l1":
            s = delta.abs().sum(dim=1) * h.abs().sum(dim=1)
        return -s.cpu()


class GradOrth(OODMethod):
    def __init__(self, model: torch.nn.Module, eps_th: float = 0.95, loss_type: str = "uniform_kl", temperature: float = 1.0, center: bool = True):
        super().__init__(model)
        self.eps_th = eps_th
        self.loss_type = loss_type
        self.temperature = temperature
        self.center = center
        self.U: Optional[torch.Tensor] = None
        self.mu: Optional[torch.Tensor] = None

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        H = h.to(next(self.model.parameters()).device)
        if self.center:
            self.mu = H.mean(dim=0, keepdim=True)
            Hc = H - self.mu
        else:
            self.mu = torch.zeros(1, H.size(1), device=H.device)
            Hc = H
        R = Hc.T
        U, S, _ = torch.linalg.svd(R, full_matrices=False)
        energy = (S ** 2)
        cum = torch.cumsum(energy, dim=0) / energy.sum()
        k = int(torch.searchsorted(cum, torch.tensor(self.eps_th, device=cum.device)).item() + 1)
        k = max(1, min(k, U.size(1)))
        self.U = U[:, :k].detach()

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.U is None or self.mu is None:
            raise RuntimeError("GradOrth.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        U = self.U.to(device)
        mu = self.mu.to(device)
        h = h.to(device)
        logits = logits.to(device)
        if self.center:
            h = h - mu
        delta = _compute_delta(logits, loss_type=self.loss_type, temperature=self.temperature)
        proj = (h @ U) @ U.T
        h_perp = h - proj
        s = torch.linalg.vector_norm(delta, ord=2, dim=1) * torch.linalg.vector_norm(h_perp, ord=2, dim=1)
        return -s.cpu()


class LowDimGradResidual(OODMethod):
    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", temperature: float = 1.0, n_components: float = 0.95, max_components: int = 256, pca_batch_size: int = 512):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.n_components = n_components
        self.max_components = max_components
        self.E: Optional[torch.Tensor] = None
        self.L: Optional[torch.Tensor] = None
        self.H_train: Optional[torch.Tensor] = None
        self.Delta_train: Optional[torch.Tensor] = None
        self.G_train_mean_row: Optional[torch.Tensor] = None
        self.G_train_mean_all: float = 0.0

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        device = next(self.model.parameters()).device
        H = h.to(device)
        logits_d = logits.to(device)
        Delta = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        
        self.H_train = H.cpu()
        self.Delta_train = Delta.cpu()
        
        G = (Delta @ Delta.T) * (H @ H.T)
        self.G_train_mean_row = G.mean(dim=1, keepdim=True)
        self.G_train_mean_all = G.mean().item()
        
        G_c = G - self.G_train_mean_row - self.G_train_mean_row.T + self.G_train_mean_all
        G_c = (G_c + G_c.T) / 2.0
        
        evals, evecs = torch.linalg.eigh(G_c)
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        
        if isinstance(self.n_components, float):
            k = int(torch.searchsorted(cum, torch.tensor(self.n_components, device=cum.device)).item() + 1)
        else:
            k = int(self.n_components)
        k = max(1, min(k, self.max_components, evecs.size(1)))
        
        self.E = evecs[:, :k].cpu()
        self.L = evals[:k].clamp_min(1e-12).cpu()

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.E is None:
            raise RuntimeError("LowDimGradResidual.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        H_test = h.to(device)
        logits_d = logits.to(device)
        Delta_test = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        
        H_train = self.H_train.to(device)
        Delta_train = self.Delta_train.to(device)
        E = self.E.to(device)
        L = self.L.to(device)
        G_mean_row = self.G_train_mean_row.to(device).squeeze(1)
        G_mean_all = self.G_train_mean_all
        
        N_test = H_test.size(0)
        scores = []
        batch_size = 512
        for i in range(0, N_test, batch_size):
            h_b = H_test[i:i+batch_size]
            d_b = Delta_test[i:i+batch_size]
            
            K_test = (d_b @ Delta_train.T) * (h_b @ H_train.T)
            K_test_c = K_test - K_test.mean(dim=1, keepdim=True) - G_mean_row.unsqueeze(0) + G_mean_all
            
            z_pca = K_test_c @ E / torch.sqrt(L)
            norm2_v = (d_b * d_b).sum(dim=1) * (h_b * h_b).sum(dim=1)
            norm2_v_c = norm2_v - 2 * K_test.mean(dim=1) + G_mean_all
            
            resid2 = norm2_v_c - (z_pca**2).sum(dim=1)
            resid = torch.sqrt(resid2.clamp_min(0))
            scores.append(resid.cpu())
            
        return torch.cat(scores, dim=0)


class GradVecMahalanobis(OODMethod):
    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", temperature: float = 1.0, n_components: float = 0.95, shrinkage: float = 1e-6, max_components: int = 256, pca_batch_size: int = 512):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.n_components = n_components
        self.shrinkage = shrinkage
        self.max_components = max_components
        self.E: Optional[torch.Tensor] = None
        self.L: Optional[torch.Tensor] = None
        self.H_train: Optional[torch.Tensor] = None
        self.Delta_train: Optional[torch.Tensor] = None
        self.G_train_mean_row: Optional[torch.Tensor] = None
        self.G_train_mean_all: float = 0.0
        self.class_stats: Dict[int, Tuple[torch.Tensor, torch.Tensor]] = {}

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        if y is None:
            raise RuntimeError("GradVecMahalanobis.fit requires labels.")
        device = next(self.model.parameters()).device
        H = h.to(device)
        logits_d = logits.to(device)
        Delta = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        
        self.H_train = H.cpu()
        self.Delta_train = Delta.cpu()
        
        G = (Delta @ Delta.T) * (H @ H.T)
        self.G_train_mean_row = G.mean(dim=1, keepdim=True)
        self.G_train_mean_all = G.mean().item()
        
        G_c = G - self.G_train_mean_row - self.G_train_mean_row.T + self.G_train_mean_all
        G_c = (G_c + G_c.T) / 2.0
        
        evals, evecs = torch.linalg.eigh(G_c)
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        
        if isinstance(self.n_components, float):
            k = int(torch.searchsorted(cum, torch.tensor(self.n_components, device=cum.device)).item() + 1)
        else:
            k = int(self.n_components)
        k = max(1, min(k, self.max_components, evecs.size(1)))
        
        self.E = evecs[:, :k].cpu()
        self.L = evals[:k].clamp_min(1e-12).cpu()
        
        E_d = self.E.to(device)
        L_d = self.L.to(device)
        Z_train = G_c @ E_d / torch.sqrt(L_d)
        
        y_np = y.reshape(-1).to(device)
        self.class_stats = {}
        class_means = {}
        Z_centered = torch.zeros_like(Z_train)
        classes = torch.unique(y_np)
        
        for c in classes:
            Z_c = Z_train[y_np == c]
            mu = Z_c.mean(dim=0)
            class_means[int(c.item())] = mu
            Z_centered[y_np == c] = Z_c - mu
            
        cov_c = (Z_centered.T @ Z_centered) / max(1, Z_train.size(0) - 1)
        cov_c = cov_c + self.shrinkage * torch.eye(Z_train.size(1), device=device)
        inv_cov = torch.linalg.inv(cov_c)
        
        for c in classes:
            self.class_stats[int(c.item())] = (class_means[int(c.item())].cpu(), inv_cov.cpu())

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.E is None or not self.class_stats:
            raise RuntimeError("GradVecMahalanobis.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        H_test = h.to(device)
        logits_d = logits.to(device)
        Delta_test = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        
        H_train = self.H_train.to(device)
        Delta_train = self.Delta_train.to(device)
        E = self.E.to(device)
        L = self.L.to(device)
        G_mean_row = self.G_train_mean_row.to(device).squeeze(1)
        G_mean_all = self.G_train_mean_all
        
        N_test = H_test.size(0)
        scores = []
        batch_size = 512
        for i in range(0, N_test, batch_size):
            h_b = H_test[i:i+batch_size]
            d_b = Delta_test[i:i+batch_size]
            
            K_test = (d_b @ Delta_train.T) * (h_b @ H_train.T)
            K_test_c = K_test - K_test.mean(dim=1, keepdim=True) - G_mean_row.unsqueeze(0) + G_mean_all
            Z_test = K_test_c @ E / torch.sqrt(L)
            
            z_scores = torch.full((Z_test.size(0),), float('inf'), device=device)
            for mu, inv_cov in self.class_stats.values():
                mu = mu.to(device)
                inv_cov = inv_cov.to(device)
                diff = Z_test - mu
                dist = torch.sqrt((diff @ inv_cov * diff).sum(dim=1).clamp_min(0))
                z_scores = torch.min(z_scores, dist)
            scores.append(z_scores.cpu())
            
        return torch.cat(scores, dim=0)


# ----------------------------
# Proposed methods (head matrix-aware)
# ----------------------------

class TwoSidedHeadGradResidual(OODMethod):
    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", temperature: float = 1.0, eps_th_u: float = 0.95, eps_th_v: float = 0.95, eps: float = 1e-12, center_h: bool = True):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.eps_th_u = eps_th_u
        self.eps_th_v = eps_th_v
        self.eps = eps
        self.center_h = center_h
        self.U: Optional[torch.Tensor] = None
        self.V: Optional[torch.Tensor] = None
        self.h_mu: Optional[torch.Tensor] = None

    @staticmethod
    def _top_eigvecs_from_cov(cov: torch.Tensor, eps_th: float) -> torch.Tensor:
        evals, evecs = torch.linalg.eigh(cov)
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        k = int(torch.searchsorted(cum, torch.tensor(eps_th, device=cum.device)).item() + 1)
        k = max(1, min(k, evecs.size(1)))
        return evecs[:, :k]

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        device = next(self.model.parameters()).device
        H = h.to(device)
        self.h_mu = H.mean(dim=0, keepdim=True) if self.center_h else torch.zeros(1, H.size(1), device=device)
        logits_d = logits.to(device)
        D = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        Hc = H - self.h_mu if self.center_h else H
        Dm = D - D.mean(dim=0, keepdim=True)
        Hm = Hc - Hc.mean(dim=0, keepdim=True)
        cov_u = (Dm.T @ Dm) / max(1, Dm.size(0) - 1)
        cov_v = (Hm.T @ Hm) / max(1, Hm.size(0) - 1)
        cov_u = cov_u + 1e-6 * torch.eye(cov_u.size(0), device=cov_u.device)
        cov_v = cov_v + 1e-6 * torch.eye(cov_v.size(0), device=cov_v.device)
        self.U = self._top_eigvecs_from_cov(cov_u, self.eps_th_u).detach()
        self.V = self._top_eigvecs_from_cov(cov_v, self.eps_th_v).detach()

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.U is None or self.V is None or self.h_mu is None:
            raise RuntimeError("TwoSidedHeadGradResidual.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        U = self.U.to(device)
        V = self.V.to(device)
        h_mu = self.h_mu.to(device)
        h_d = h.to(device)
        if self.center_h:
            h_d = h_d - h_mu
        logits_d = logits.to(device)
        delta = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        nd = torch.linalg.vector_norm(delta, ord=2, dim=1).clamp_min(self.eps)
        nh = torch.linalg.vector_norm(h_d, ord=2, dim=1).clamp_min(self.eps)
        d_hat = delta / nd.unsqueeze(1)
        h_hat = h_d / nh.unsqueeze(1)
        p_d = (d_hat @ U) @ U.T
        p_h = (h_hat @ V) @ V.T
        dp = (d_hat * p_d).sum(dim=1)
        hp = (h_hat * p_h).sum(dim=1)
        r2 = 1.0 - dp * hp
        r = torch.sqrt(r2.clamp_min(0.0))
        return r.cpu()


class TwoSidedHeadGradCodeMahalanobis(OODMethod):
    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", temperature: float = 1.0, eps_th_u: float = 0.95, eps_th_v: float = 0.95, shrinkage: float = 1e-6, include_log_mag: bool = True, eps: float = 1e-12, center_h: bool = True):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.eps_th_u = eps_th_u
        self.eps_th_v = eps_th_v
        self.shrinkage = shrinkage
        self.include_log_mag = include_log_mag
        self.eps = eps
        self.center_h = center_h
        self.U: Optional[torch.Tensor] = None
        self.V: Optional[torch.Tensor] = None
        self.h_mu: Optional[torch.Tensor] = None
        self.class_stats: Dict[int, Tuple[np.ndarray, np.ndarray]] = {}

    @staticmethod
    def _top_eigvecs_from_cov(cov: torch.Tensor, eps_th: float) -> torch.Tensor:
        evals, evecs = torch.linalg.eigh(cov)
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        k = int(torch.searchsorted(cum, torch.tensor(eps_th, device=cum.device)).item() + 1)
        k = max(1, min(k, evecs.size(1)))
        return evecs[:, :k]

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        if y is None:
            raise RuntimeError("TwoSidedHeadGradCodeMahalanobis.fit requires labels.")
        device = next(self.model.parameters()).device
        H = h.to(device)
        self.h_mu = H.mean(dim=0, keepdim=True) if self.center_h else torch.zeros(1, H.size(1), device=device)
        logits_d = logits.to(device)
        D = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        Hc = H - self.h_mu if self.center_h else H
        Dm = D - D.mean(dim=0, keepdim=True)
        Hm = Hc - Hc.mean(dim=0, keepdim=True)
        cov_u = (Dm.T @ Dm) / max(1, Dm.size(0) - 1)
        cov_v = (Hm.T @ Hm) / max(1, Hm.size(0) - 1)
        cov_u = cov_u + 1e-6 * torch.eye(cov_u.size(0), device=cov_u.device)
        cov_v = cov_v + 1e-6 * torch.eye(cov_v.size(0), device=cov_v.device)
        self.U = self._top_eigvecs_from_cov(cov_u, self.eps_th_u).detach()
        self.V = self._top_eigvecs_from_cov(cov_v, self.eps_th_v).detach()

        nd = torch.linalg.vector_norm(D, ord=2, dim=1).clamp_min(self.eps)
        nh = torch.linalg.vector_norm(Hc, ord=2, dim=1).clamp_min(self.eps)
        d_hat = D / nd.unsqueeze(1)
        h_hat = Hc / nh.unsqueeze(1)
        c_u = d_hat @ self.U
        c_v = h_hat @ self.V
        code = torch.cat([c_u, c_v], dim=1)
        if self.include_log_mag:
            logmag = (torch.log(nd) + torch.log(nh)).unsqueeze(1)
            code = torch.cat([code, logmag], dim=1)
            
        Xr = code.cpu().numpy()
        y_np = y.reshape(-1).cpu().numpy()
        self.class_stats = {}
        class_means = {}
        Xr_centered = np.zeros_like(Xr)
        for c in np.unique(y_np):
            Xc_c = Xr[y_np == c]
            mu = Xc_c.mean(axis=0)
            class_means[int(c)] = mu
            Xr_centered[y_np == c] = Xc_c - mu
            
        cov_c = np.cov(Xr_centered, rowvar=False) + self.shrinkage * np.eye(Xr.shape[1])
        inv_cov = np.linalg.inv(cov_c)
        for c in np.unique(y_np):
            self.class_stats[int(c)] = (class_means[int(c)], inv_cov)

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.U is None or self.V is None or self.h_mu is None or not self.class_stats:
            raise RuntimeError("TwoSidedHeadGradCodeMahalanobis.fit must be called.")
        device = next(self.model.parameters()).device
        U = self.U.to(device)
        V = self.V.to(device)
        h_mu = self.h_mu.to(device)
        h_d = h.to(device)
        if self.center_h:
            h_d = h_d - h_mu
        logits_d = logits.to(device)
        delta = _compute_delta(logits_d, loss_type=self.loss_type, temperature=self.temperature)
        nd = torch.linalg.vector_norm(delta, ord=2, dim=1).clamp_min(self.eps)
        nh = torch.linalg.vector_norm(h_d, ord=2, dim=1).clamp_min(self.eps)
        d_hat = delta / nd.unsqueeze(1)
        h_hat = h_d / nh.unsqueeze(1)
        c_u = d_hat @ U
        c_v = h_hat @ V
        code = torch.cat([c_u, c_v], dim=1)
        if self.include_log_mag:
            logmag = (torch.log(nd) + torch.log(nh)).unsqueeze(1)
            code = torch.cat([code, logmag], dim=1)
        Z = code.cpu().numpy()
        scores = []
        for i in range(Z.shape[0]):
            zi = Z[i]
            best = np.inf
            for mu, inv_cov in self.class_stats.values():
                d = zi - mu
                md = float(np.sqrt(d.T @ inv_cov @ d))
                best = min(best, md)
            scores.append(best)
        return torch.tensor(scores)


class FeatureGMM(OODMethod):
    def __init__(self, model: torch.nn.Module, n_components: int = 5):
        super().__init__(model)
        self.n_components = n_components
        self.gmm: Optional[GaussianMixture] = None

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        X = h.cpu().numpy()
        self.gmm = GaussianMixture(n_components=self.n_components, covariance_type='diag', random_state=42)
        self.gmm.fit(X)

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.gmm is None:
            raise RuntimeError("FeatureGMM.fit must be called before scoring.")
        log_prob = self.gmm.score_samples(h.cpu().numpy())
        return torch.from_numpy(-log_prob).float()


class FeaturePCA(OODMethod):
    def __init__(self, model: torch.nn.Module, n_components: float = 0.95):
        super().__init__(model)
        self.n_components = n_components
        self.pca_evecs: Optional[torch.Tensor] = None
        self.u_mean: Optional[torch.Tensor] = None

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        device = next(self.model.parameters()).device
        H = h.to(device)
        self.u_mean = H.mean(dim=0, keepdim=True)
        H_c = H - self.u_mean
        cov = (H_c.T @ H_c) / max(1, H_c.size(0) - 1)
        evals, evecs = torch.linalg.eigh(cov)
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        k = int(torch.searchsorted(cum, torch.tensor(self.n_components, device=cum.device)).item() + 1)
        k = max(1, min(k, evecs.size(1)))
        self.pca_evecs = evecs[:, :k]

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.pca_evecs is None or self.u_mean is None:
            raise RuntimeError("FeaturePCA.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        evecs = self.pca_evecs.to(device)
        u_mean = self.u_mean.to(device)
        h_d = h.to(device)
        h_c = h_d - u_mean
        proj = (h_c @ evecs) @ evecs.T
        resid = torch.linalg.vector_norm(h_c - proj, ord=2, dim=1)
        return resid.cpu()


class ReAct(OODMethod):
    def __init__(self, model: torch.nn.Module, p: float = 90.0, temperature: float = 1.0):
        super().__init__(model)
        self.p = p
        self.temperature = temperature
        self.threshold: Optional[float] = None
        self.head = HeadExtractor(model).head

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        X = h.cpu().numpy()
        self.threshold = float(np.percentile(X, self.p))

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.threshold is None:
            raise RuntimeError("ReAct.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        h_d = h.to(device)
        h_clipped = torch.clamp(h_d, max=self.threshold)
        logits_clipped = self.head(h_clipped)
        logits_out = logits_clipped / self.temperature
        energy = -torch.logsumexp(logits_out, dim=1)
        return energy.cpu()


class ViM(OODMethod):
    def __init__(self, model: torch.nn.Module, dim: Optional[int] = None):
        super().__init__(model)
        self.dim = dim 
        self.alpha: Optional[float] = None
        self.evecs_residual: Optional[torch.Tensor] = None
        self.u_mean: Optional[torch.Tensor] = None

    def fit_features(self, h: torch.Tensor, logits: torch.Tensor, y: Optional[torch.Tensor] = None):
        H = h
        Logits = logits
        self.u_mean = H.mean(dim=0, keepdim=True)
        H_c = H - self.u_mean
        K = Logits.size(1)
        cov = (H_c.T @ H_c) / max(1, H_c.size(0) - 1)
        evals, evecs = torch.linalg.eigh(cov)
        idx = torch.argsort(evals, descending=True)
        evecs = evecs[:, idx]
        if self.dim is None:
            self.dim = H.size(1) - K
        dim = max(1, min(self.dim, H.size(1) - 1))
        self.evecs_residual = evecs[:, dim:]
        residuals = torch.linalg.vector_norm(H_c @ self.evecs_residual, ord=2, dim=1)
        energies = torch.logsumexp(Logits, dim=1)
        self.alpha = (energies.mean() / residuals.mean().clamp_min(1e-8)).item()

    def compute_ood_scores_features(self, h: torch.Tensor, logits: torch.Tensor) -> torch.Tensor:
        if self.alpha is None or self.evecs_residual is None or self.u_mean is None:
            raise RuntimeError("ViM.fit must be called before scoring.")
        evecs_r = self.evecs_residual
        u_m = self.u_mean
        h_c = h - u_m
        res = torch.linalg.vector_norm(h_c @ evecs_r, ord=2, dim=1)
        v_logit = res * self.alpha
        energy = torch.logsumexp(logits, dim=1)
        vim_score = v_logit - energy
        return vim_score.cpu()

# ----------------------------
# Convenience registry
# ----------------------------

def build_method_registry(model: torch.nn.Module) -> Dict[str, OODMethod]:
    """Return a dict of name -> instantiated method with default hyperparameters."""
    return {
        "msp": MSP(model),
        "energy": EnergyBased(model),
        "odin": Odin(model),
        "feat_knn": FeatureKNN(model, k=10),
        "feat_maha": FeatureMahalanobis(model),
        "feat_gmm": FeatureGMM(model, n_components=5),
        "feat_pca": FeaturePCA(model, n_components=0.95),
        "react": ReAct(model, p=90.0),
        "vim": ViM(model),
        "gradnorm": GradNorm(model, loss_type="uniform_kl", p="fro"),
        "gradorth": GradOrth(model, eps_th=0.95, loss_type="uniform_kl"),
        "lowdim_grad_resid": LowDimGradResidual(model, loss_type="uniform_kl", n_components=0.95),
        "gradvec_maha": GradVecMahalanobis(model, loss_type="uniform_kl", n_components=0.95),
        "twosided_resid": TwoSidedHeadGradResidual(model, loss_type="uniform_kl", eps_th_u=0.95, eps_th_v=0.95),
        "twosided_code_maha": TwoSidedHeadGradCodeMahalanobis(model, loss_type="uniform_kl", eps_th_u=0.95, eps_th_v=0.95),
    }


if __name__ == "__main__":
    # Minimal smoke test with a toy model
    class SimpleModel(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.fc1 = torch.nn.Linear(10, 20)
            self.fc2 = torch.nn.Linear(20, 10)
            self.fc3 = torch.nn.Linear(10, 5)

        def forward(self, x):
            x = torch.relu(self.fc1(x))
            x = torch.relu(self.fc2(x))
            return self.fc3(x)

    torch.manual_seed(0)
    model = SimpleModel()

    # Create a fake ID loader
    id_samples = [(torch.randn(8, 10), torch.randint(0, 5, (8,))) for _ in range(10)]
    ood_samples = [(torch.randn(8, 10) + 2.0, torch.randint(0, 5, (8,))) for _ in range(5)]

    methods = build_method_registry(model)

    # Fit those that need fitting
    for name, m in methods.items():
        try:
            m.fit(id_samples)
        except Exception:
            pass

    # Score
    for name, m in methods.items():
        try:
            s_id = m.compute_ood_scores(id_samples)
            s_ood = m.compute_ood_scores(ood_samples)
            print(f"{name:20s} | id_mean={s_id.mean():.3f} ood_mean={s_ood.mean():.3f}")
        except Exception as e:
            print(f"{name:20s} | skipped ({e})")
